VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# A default 32u4 build is more than 8k oversized,
# so we have to disable some less-common / expert-level features.
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = no
DYNAMIC_MACRO_ENABLE = yes
OLED_ENABLE = no
COMMAND_ENABLE = no

AUTO_SHIFT_ENABLE = no
RGBLIGHT_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no
CAPS_WORD_ENABLE = yes