VIA_ENABLE = yes
VIAL_ENABLE = yes

ENCODER_MAP_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
#SEND_STRING_ENABLE = yes
CAPS_WORD_ENABLE = yes